steps:
  # Dockerイメージの作成
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '-t', "gcr.io/$PROJECT_ID/crypt-cat$_STAGING:$COMMIT_SHA",
            "--build-arg","_IS_ACTUALLY_SELL_BUY=$_IS_ACTUALLY_SELL_BUY",
            "--build-arg","_SELL_BUY_AMOUNT=$_SELL_BUY_AMOUNT",
            "--build-arg","_SELL_BUY_PRICE=$_SELL_BUY_PRICE",
            "--build-arg","_IS_ORDER_RETRY=$_IS_ORDER_RETRY",
            "--build-arg","_RETRY_DELAY_SEC=$_RETRY_DELAY_SEC",
            "--build-arg","_RETRY_LIMIT_COUNT=$_RETRY_LIMIT_COUNT",
            '.' ]
  # DockerイメージをContainer RegistryへPush
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/crypt-cat$_STAGING:$COMMIT_SHA' ]
  # DockerイメージをClourd Runへデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "crypt-cat$_STAGING"
      - "--image"
      - "gcr.io/$PROJECT_ID/crypt-cat$_STAGING:$COMMIT_SHA"
      - "--region"
      - "asia-northeast1"
images:
  - "gcr.io/$PROJECT_ID/crypt-cat$_STAGING:$COMMIT_SHA"