# ブラウザ Cookie（sessionid）
BROWSER_SESSIONID = 'かきかえる'

# ヘッドレスで実行するか
IS_HEADLESS = False

# 起動後変更待ち時間
START_WAITING_SEC = 15

# パラメータ設定
PARAMETER_1_USE = True
PARAMETER_2_USE = True

# 所要時間 繰り返し回数 * 繰り返し回数 * 3sec
# およそ1150件 / hour
PARAMETER_1_KEY = 'ATR Period'
PARAMETER_1_START_VALUE = 1
PARAMETER_1_MAX_VALUE = 30
PARAMETER_1_INCREMENTAL_VALUE = 1

PARAMETER_2_KEY = 'ATR Multiplier'
PARAMETER_2_START_VALUE = 1
PARAMETER_2_MAX_VALUE = 30
PARAMETER_2_INCREMENTAL_VALUE = 1